name: CI for Go Code #Naming the workflow
on: #for event triggering
  push:
    branches: [main]  #add commas for more branches to monitor
  pull_request:
    branches: [main]
    
jobs: # job to execute?
  build: # name of the job
    name: Load OS # name for printing
    runs-on: ubuntu-latest  # specify OS in virtual machine
    steps: 
    - name: Print hello
      run: |  # run terminal commands
        ls
        echo Hello!!
        
    - name: Setup Go
      uses: actions/setup-go@v3.2.0
      with:
        go-version: 1.18
    - name: Check Go Version
      run: go version
      
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Check File System
      run: ls
      
    
